### PR TITLE
hidden spoilers at first.

### PR DESCRIPTION
**Pull request by pypp**
hide spoilers trivia and when the user clicks "I can handle the truth" the spoilers will be showed.

Screenshot 2022-07-09 222634

### CODE REVIEW

**Comment by combatwombat** [comment]
Good idea if there's lots of trivia so you might overlook the orange "Spoilers" header. I can't merge it like this, since it modifies the files in dist, which are generated by the build script. Should be in src/ instead, I'll rewrite it a bit and maybe add an options page. Thanks for the contribution!

**Comment by pypp** [comment]
> Good idea if there's lots of trivia so you might overlook the orange "Spoilers" header. I can't merge it like this, since it modifies the files in dist, which are generated by the build script. Should be in src/ instead, I'll rewrite it a bit and maybe add an options page. Thanks for the contribution!

I'm gonna fix the commit and open a new PR.

**Comment by pypp** [comment]
Fixed the previous commit.

**Comment by combatwombat** [comment]
I went a different route, with button and options page:
Bildschirmfoto 2022-07-16 um 15 18 58
Bildschirmfoto 2022-07-16 um 15 19 10

It's easier to click and not everyone wants spoilers hidden. So I won't merge yours, but you're mentioned in the readme, I hope that's ok. Thanks for the suggestion and code.

**Comment by pypp** [comment]
> I went a different route, with button and options page: Bildschirmfoto 2022-07-16 um 15 18 58 Bildschirmfoto 2022-07-16 um 15 19 10
> 
> It's easier to click and not everyone wants spoilers hidden. So I won't merge yours, but you're mentioned in the readme, I hope that's ok. Thanks for the suggestion and code.

That looks Great 👍🏼

**Pull request closed without merging**
